#ifndef GENERATED_FRIKAN_MODEL_DATA_H
#define GENERATED_FRIKAN_MODEL_DATA_H

#include <stdint.h>

typedef float port_float;

#define FRIKAN_INPUT_DIM {{FRIKAN_INPUT_DIM}}u
#define FRIKAN_FEATURES {{FRIKAN_FEATURES}}u
#define FRIKAN_KAN_LAYER_COUNT {{FRIKAN_KAN_LAYER_COUNT}}u
#define FRIKAN_MAX_LAYER_INPUTS {{FRIKAN_MAX_LAYER_INPUTS}}u
#define FRIKAN_MAX_LAYER_OUTPUTS {{FRIKAN_MAX_LAYER_OUTPUTS}}u
#define FRIKAN_MAX_GRID_INTERVALS {{FRIKAN_MAX_GRID_INTERVALS}}u
#define FRIKAN_MAX_SPLINE_KERNELS {{FRIKAN_MAX_SPLINE_KERNELS}}u
#define FRIKAN_USE_LUT {{FRIKAN_USE_LUT}}u
#define FRIKAN_LUT_POINTS {{FRIKAN_LUT_POINTS}}u
#define FRIKAN_LUT_INTERPOLATION {{FRIKAN_LUT_INTERPOLATION}}u
#define FRIKAN_USE_SYMMETRY {{FRIKAN_USE_SYMMETRY}}u
#define FRIKAN_USE_EVEN {{FRIKAN_USE_EVEN}}u
#define OUTPUT_UNITS {{OUTPUT_UNITS}}u
#define BENCHMARK_ITERATIONS {{BENCHMARK_ITERATIONS}}u
#define BENCHMARK_REPEAT_RUNS {{BENCHMARK_REPEAT_RUNS}}u
#define BENCHMARK_RESET_STATE_EACH_RUN {{BENCHMARK_RESET_STATE_EACH_RUN}}u
#define VALIDATION_RECORD_COUNT {{VALIDATION_RECORD_COUNT}}u
#define VALIDATION_SEQ_LEN {{VALIDATION_SEQ_LEN}}u

#define SCALER_INPUT_DATA_RANGE {{SCALER_INPUT_DATA_RANGE}}
#define SCALER_OUTPUT_DATA_RANGE {{SCALER_OUTPUT_DATA_RANGE}}

static const port_float validation_input[VALIDATION_RECORD_COUNT][VALIDATION_SEQ_LEN][FRIKAN_INPUT_DIM] = {{VALIDATION_INPUT_INITIALIZER}};

static const uint16_t frikan_layer_input_dims[FRIKAN_KAN_LAYER_COUNT] = {{LAYER_INPUT_DIMS_INITIALIZER}};

static const uint16_t frikan_layer_output_dims[FRIKAN_KAN_LAYER_COUNT] = {{LAYER_OUTPUT_DIMS_INITIALIZER}};

static const port_float frikan_iir_b0[FRIKAN_FEATURES] = {{FRIKAN_IIR_B0_INITIALIZER}};

static const port_float frikan_iir_b1[FRIKAN_FEATURES] = {{FRIKAN_IIR_B1_INITIALIZER}};

static const port_float frikan_iir_b2[FRIKAN_FEATURES] = {{FRIKAN_IIR_B2_INITIALIZER}};

static const port_float frikan_iir_a1[FRIKAN_FEATURES] = {{FRIKAN_IIR_A1_INITIALIZER}};

static const port_float frikan_iir_a2[FRIKAN_FEATURES] = {{FRIKAN_IIR_A2_INITIALIZER}};

static const port_float frikan_layer_bias[FRIKAN_KAN_LAYER_COUNT][FRIKAN_MAX_LAYER_OUTPUTS] = {{FRIKAN_LAYER_BIAS_INITIALIZER}};

{{FRIKAN_LAYER_DATA_ARRAYS}}

#endif
