#ifndef GENERATED_LSTM_TRANSFORMER_MODEL_DATA_H
#define GENERATED_LSTM_TRANSFORMER_MODEL_DATA_H

#include <stdint.h>

typedef float port_float;

#define ACT_LINEAR 0u
#define ACT_RELU 1u
#define ACT_TANH 2u
#define ACT_SIGMOID 3u
#define ACT_SILU 4u

#define LSTM_INPUT_DIM {{LSTM_INPUT_DIM}}u
#define LSTM_UNITS {{LSTM_UNITS}}u
#define TRANSFORMER_LAYER_COUNT {{TRANSFORMER_LAYER_COUNT}}u
#define TRANSFORMER_HEADS {{TRANSFORMER_HEADS}}u
#define TRANSFORMER_KEY_DIM {{TRANSFORMER_KEY_DIM}}u
#define TRANSFORMER_FF_DIM {{TRANSFORMER_FF_DIM}}u
#define ATTENTION_POOL_SIZE {{ATTENTION_POOL_SIZE}}u
#define TRANSFORMER_CONTEXT_LEN {{TRANSFORMER_CONTEXT_LEN}}u
#define ATTENTION_SCALE {{ATTENTION_SCALE}}
#define TRANSFORMER_LAYER_NORM_EPSILON {{TRANSFORMER_LAYER_NORM_EPSILON}}
#define HAS_POST_DENSE {{HAS_POST_DENSE}}u
#define POST_DENSE_INPUT_UNITS {{POST_DENSE_INPUT_UNITS}}u
#define POST_DENSE_UNITS {{POST_DENSE_UNITS}}u
#define POST_DENSE_ACTIVATION {{POST_DENSE_ACTIVATION}}u
#define OUTPUT_INPUT_UNITS {{OUTPUT_INPUT_UNITS}}u
#define OUTPUT_UNITS {{OUTPUT_UNITS}}u
#define BENCHMARK_ITERATIONS {{BENCHMARK_ITERATIONS}}u
#define BENCHMARK_REPEAT_RUNS {{BENCHMARK_REPEAT_RUNS}}u
#define BENCHMARK_RESET_STATE_EACH_RUN {{BENCHMARK_RESET_STATE_EACH_RUN}}u
#define VALIDATION_RECORD_COUNT {{VALIDATION_RECORD_COUNT}}u
#define VALIDATION_SEQ_LEN {{VALIDATION_SEQ_LEN}}u

#define SCALER_INPUT_DATA_RANGE {{SCALER_INPUT_DATA_RANGE}}
#define SCALER_OUTPUT_DATA_RANGE {{SCALER_OUTPUT_DATA_RANGE}}

static const port_float validation_input[VALIDATION_RECORD_COUNT][VALIDATION_SEQ_LEN][LSTM_INPUT_DIM] = {{VALIDATION_INPUT_INITIALIZER}};

static const port_float lstm_kernel[LSTM_INPUT_DIM][LSTM_UNITS * 4u] = {{LSTM_KERNEL_INITIALIZER}};

static const port_float lstm_recurrent_kernel[LSTM_UNITS][LSTM_UNITS * 4u] = {{LSTM_RECURRENT_KERNEL_INITIALIZER}};

static const port_float lstm_bias[LSTM_UNITS * 4u] = {{LSTM_BIAS_INITIALIZER}};

static const port_float transformer_query_kernel[TRANSFORMER_LAYER_COUNT][LSTM_UNITS][TRANSFORMER_HEADS][TRANSFORMER_KEY_DIM] = {{TRANSFORMER_QUERY_KERNEL_INITIALIZER}};

static const port_float transformer_query_bias[TRANSFORMER_LAYER_COUNT][TRANSFORMER_HEADS][TRANSFORMER_KEY_DIM] = {{TRANSFORMER_QUERY_BIAS_INITIALIZER}};

static const port_float transformer_key_kernel[TRANSFORMER_LAYER_COUNT][LSTM_UNITS][TRANSFORMER_HEADS][TRANSFORMER_KEY_DIM] = {{TRANSFORMER_KEY_KERNEL_INITIALIZER}};

static const port_float transformer_key_bias[TRANSFORMER_LAYER_COUNT][TRANSFORMER_HEADS][TRANSFORMER_KEY_DIM] = {{TRANSFORMER_KEY_BIAS_INITIALIZER}};

static const port_float transformer_value_kernel[TRANSFORMER_LAYER_COUNT][LSTM_UNITS][TRANSFORMER_HEADS][TRANSFORMER_KEY_DIM] = {{TRANSFORMER_VALUE_KERNEL_INITIALIZER}};

static const port_float transformer_value_bias[TRANSFORMER_LAYER_COUNT][TRANSFORMER_HEADS][TRANSFORMER_KEY_DIM] = {{TRANSFORMER_VALUE_BIAS_INITIALIZER}};

static const port_float transformer_attention_output_kernel[TRANSFORMER_LAYER_COUNT][TRANSFORMER_HEADS][TRANSFORMER_KEY_DIM][LSTM_UNITS] = {{TRANSFORMER_ATTENTION_OUTPUT_KERNEL_INITIALIZER}};

static const port_float transformer_attention_output_bias[TRANSFORMER_LAYER_COUNT][LSTM_UNITS] = {{TRANSFORMER_ATTENTION_OUTPUT_BIAS_INITIALIZER}};

static const port_float transformer_ln_attn_gamma[TRANSFORMER_LAYER_COUNT][LSTM_UNITS] = {{TRANSFORMER_LN_ATTN_GAMMA_INITIALIZER}};

static const port_float transformer_ln_attn_beta[TRANSFORMER_LAYER_COUNT][LSTM_UNITS] = {{TRANSFORMER_LN_ATTN_BETA_INITIALIZER}};

static const port_float transformer_ffn_expand_kernel[TRANSFORMER_LAYER_COUNT][LSTM_UNITS][TRANSFORMER_FF_DIM] = {{TRANSFORMER_FFN_EXPAND_KERNEL_INITIALIZER}};

static const port_float transformer_ffn_expand_bias[TRANSFORMER_LAYER_COUNT][TRANSFORMER_FF_DIM] = {{TRANSFORMER_FFN_EXPAND_BIAS_INITIALIZER}};

static const port_float transformer_ffn_project_kernel[TRANSFORMER_LAYER_COUNT][TRANSFORMER_FF_DIM][LSTM_UNITS] = {{TRANSFORMER_FFN_PROJECT_KERNEL_INITIALIZER}};

static const port_float transformer_ffn_project_bias[TRANSFORMER_LAYER_COUNT][LSTM_UNITS] = {{TRANSFORMER_FFN_PROJECT_BIAS_INITIALIZER}};

static const port_float transformer_ln_ffn_gamma[TRANSFORMER_LAYER_COUNT][LSTM_UNITS] = {{TRANSFORMER_LN_FFN_GAMMA_INITIALIZER}};

static const port_float transformer_ln_ffn_beta[TRANSFORMER_LAYER_COUNT][LSTM_UNITS] = {{TRANSFORMER_LN_FFN_BETA_INITIALIZER}};

static const port_float post_dense_kernel[POST_DENSE_INPUT_UNITS][POST_DENSE_UNITS] = {{POST_DENSE_KERNEL_INITIALIZER}};

static const port_float post_dense_bias[POST_DENSE_UNITS] = {{POST_DENSE_BIAS_INITIALIZER}};

static const port_float output_kernel[OUTPUT_INPUT_UNITS][OUTPUT_UNITS] = {{OUTPUT_KERNEL_INITIALIZER}};

static const port_float output_bias[OUTPUT_UNITS] = {{OUTPUT_BIAS_INITIALIZER}};

#endif
