#ifndef GENERATED_TCN_MODEL_DATA_H
#define GENERATED_TCN_MODEL_DATA_H

#include <stdint.h>

typedef float port_float;

#define ACT_LINEAR 0u
#define ACT_RELU 1u
#define ACT_TANH 2u
#define ACT_SIGMOID 3u
#define ACT_SILU 4u

#define TCN_INPUT_DIM {{TCN_INPUT_DIM}}u
#define TCN_BLOCK_COUNT {{TCN_BLOCK_COUNT}}u
#define TCN_OUTPUT_UNITS {{TCN_OUTPUT_UNITS}}u
#define TCN_HAS_INITIAL_PROJECTION {{TCN_HAS_INITIAL_PROJECTION}}u
#define TCN_HAS_CHANNEL_PROJECTION {{TCN_HAS_CHANNEL_PROJECTION}}u
#define TCN_HAS_OUTPUT_CONV {{TCN_HAS_OUTPUT_CONV}}u
#define BENCHMARK_ITERATIONS {{BENCHMARK_ITERATIONS}}u
#define BENCHMARK_REPEAT_RUNS {{BENCHMARK_REPEAT_RUNS}}u
#define BENCHMARK_RESET_STATE_EACH_RUN {{BENCHMARK_RESET_STATE_EACH_RUN}}u
#define VALIDATION_RECORD_COUNT {{VALIDATION_RECORD_COUNT}}u
#define VALIDATION_SEQ_LEN {{VALIDATION_SEQ_LEN}}u

#define SCALER_INPUT_DATA_RANGE {{SCALER_INPUT_DATA_RANGE}}
#define SCALER_OUTPUT_DATA_RANGE {{SCALER_OUTPUT_DATA_RANGE}}

static const port_float validation_input[VALIDATION_RECORD_COUNT][VALIDATION_SEQ_LEN][TCN_INPUT_DIM] = {{VALIDATION_INPUT_INITIALIZER}};

{{INITIAL_PROJECTION_DECL}}{{CHANNEL_PROJECTION_DECL}}{{BLOCK_DECLS}}{{POST_LAYER_DECLS}}{{OUTPUT_DECLS}}#endif
