#ifndef GENERATED_WAVENET_MODEL_DATA_H
#define GENERATED_WAVENET_MODEL_DATA_H

#include <stdint.h>

typedef float port_float;

#define ACT_LINEAR 0u
#define ACT_RELU 1u
#define ACT_TANH 2u
#define ACT_SIGMOID 3u
#define ACT_SILU 4u

#define WAVENET_INPUT_DIM {{WAVENET_INPUT_DIM}}u
#define BENCHMARK_ITERATIONS {{BENCHMARK_ITERATIONS}}u
#define BENCHMARK_REPEAT_RUNS {{BENCHMARK_REPEAT_RUNS}}u
#define BENCHMARK_RESET_STATE_EACH_RUN {{BENCHMARK_RESET_STATE_EACH_RUN}}u
#define VALIDATION_RECORD_COUNT {{VALIDATION_RECORD_COUNT}}u
#define VALIDATION_SEQ_LEN {{VALIDATION_SEQ_LEN}}u

#define SCALER_INPUT_DATA_RANGE {{SCALER_INPUT_DATA_RANGE}}
#define SCALER_OUTPUT_DATA_RANGE {{SCALER_OUTPUT_DATA_RANGE}}

static const port_float validation_input[VALIDATION_RECORD_COUNT][VALIDATION_SEQ_LEN][WAVENET_INPUT_DIM] = {{VALIDATION_INPUT_INITIALIZER}};

static const port_float wavenet_initial_kernel[{{INITIAL_KERNEL_SIZE}}u][{{INITIAL_INPUT_CHANNELS}}u][{{INITIAL_OUTPUT_CHANNELS}}u] = {{INITIAL_KERNEL_INITIALIZER}};

static const port_float wavenet_initial_bias[{{INITIAL_OUTPUT_CHANNELS}}u] = {{INITIAL_BIAS_INITIALIZER}};

{{BLOCK_LAYER_DECLS}}{{POST_LAYER_DECLS}}{{OUTPUT_DECLS}}#endif
