/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __MET_SignalGenerator__H
#define __MET_SignalGenerator__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_MET_SignalGenerator(Args *args);

void MET_SignalGenerator_disable(PikaObj *self);
void MET_SignalGenerator_enable(PikaObj *self);
void MET_SignalGenerator_setAmp(PikaObj *self, pika_float A);
void MET_SignalGenerator_setFre(PikaObj *self, pika_float f);

#endif
