/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __MET_Process__H
#define __MET_Process__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_MET_Process(Args *args);

void MET_Process_disableWp(PikaObj *self);
void MET_Process_enableWp(PikaObj *self);

#endif
